### ISSUE TITLE
[Caching] Allow user to disable time based cache invalidations.

### ISSUE THREAD

**Issue by AraHaan** [Nihlus/Remora.Discord#101]
**Description**
So, on my small bot I basically intended for the cache library / package to invalidate certain elements of the cache based on the following situations:
- GuildMembers: When a *new* user joins/leaves a guild (add/remove it from cache) (GUILD_MEMER_JOIN / GUILD_MEMBER_REMOVE)
- Roles: When a *new* role is added to/removed from the guild (add/remove it from cache) (aka GUILD_ROLE_ADD / GUILD_ROLE_DELETE events)
- Guild: When you try to obtain the ``IGuild`` instance from a snowflake (add it to the cache if not already)

However it seems that after some seconds that those entries get auto removed from the cache, I expected them to only be removed when the above 4 (or possibly more) events happen. I depend on them being kept in the cache unless those events happen to *invalidate* them from the cache as I basically have a timer in my code (System.Threading.Timers.Timer set to the lowest invocation setting possible to repeat itself over and over again) which calls:

- RestGuildApi.GetGuildMemberAsync (To get the guild user)

And then it compares between some local json stuff to check if:
- the user needs to have certain roles of theirs removed (my way to trying to implement roles that expire every month/year)

**Why This is Needed**
This is needed because what I *expected* vs what I actually got was different and instead resulted in getting API Blocked after ~3 days of running the bot. I have no idea why it all of a sudden decided *now* was the time to get me API Blocked.

**Alternatives Considered**

I do not know if there is another way to solve it (other than trying to implement cache myself which would be counter productive with a small bot like mine).

**Additional Details**

**Comment by Rutherther** [comment]
Currently you could configure `CacheSettings` to set the time of expiration to a large value. https://github.com/Nihlus/Remora.Discord/blob/master/Backend/Remora.Discord.Caching/Services/CacheSettings.cs#L84

However if it was possible to make these values null, then it would be possible to make it never expire.

**Comment by AraHaan** [comment]
I agree, I guess ``null`` should make the thing not try to do time based expiration of the caches.

**Comment by Tylertron1998** [comment]
-1 instead of null seems like a more consistent option (Think of `Task.Delay(-1)`) in my opinion.

**Comment by Rutherther** [comment]
Well I think the least confusing solution would be to make it `DateTimeOffset` and use this value https://docs.microsoft.com/en-us/dotnet/api/system.runtime.caching.objectcache.infiniteabsoluteexpiration?view=dotnet-plat-ext-5.0 (that is just mapped to DateTimeOffset.MaxValue)

But I am not sure whether TimeSpan was used because of any reason
