### ISSUE TITLE
Use ICommandContext.GuildId in type parsers rather than retrieving guildId using channelAPI

### ISSUE THREAD

**Issue by Rutherther** [Nihlus/Remora.Discord#102]
**Description**
`RoleParser` and `GuildMemberParser` currently retrieve channel id from command context, obtain that channel using channelApi, then get guildId of that channel and continue with that id. The first step could be skipped by using `ICommandContext.GuildId` directly, avoiding call to channelApi.

**Why This is Needed**
To reduce calls to Discord Api that are not needed.

**Comment by AraHaan** [comment]
I would go through all of the parsers to look for needless api calls to reduce the possible chance of ratelimiting or getting temp api banned by cloudflare as much as possible, if it can be done.

**Comment by Nihlus** [comment]
@AraHaan Rate limiting or API banning by cloudflare is not possible, barring a bug in the preemptive rate limit policy. That said, fixing this still saves an API call or two, which is good :)
