### ISSUE TITLE
Create browsable documentation

### ISSUE THREAD

**Issue by Nihlus** [Nihlus/Remora.Discord#11]
There is currently no documentation of the library and its usage, save for an example bot and in-source XML documentation headers. While these are useful, a browsable documentation site should be created with

1. API documentation extracted from the XML comments
2. Handwritten guides, tutorials, explanations, etc

**Comment by FireCubeStudios** [comment]
can i try this to be assigned?

**Comment by Nihlus** [comment]
@FireCubeStudios Go for it! Feel free to open up a WIP pull request at any time.

Ideally, the docs should be autogenerated as a build step or github action, and published to the `gh-pages` branch so people can view it.

**Comment by FireCubeStudios** [comment]
> Ideally, the docs should be autogenerated as a build step or github action, 
i dont know how to do this. my idea is creating markdown files with the docs. Maybe there is a better way i am new to open source

**Comment by Nihlus** [comment]
@FireCubeStudios Generally, API documentation is automatically generated from the XML documentation in the source code itself. Adding handwritten markdown files is a good idea, but those should contain information about how to use the library - examples, tutorials, quickstarts, etc - I'd love to have those :)

**Comment by Nihlus** [comment]
This has been implemented, and is available at https://nihlus.github.io/Remora.Discord/.
