### ISSUE TITLE
Occasionally receiving "The payload after identification was not a Ready payload." on reconnect

### ISSUE THREAD

**Issue by Cyberboss** [Nihlus/Remora.Discord#119]
Still working on a reproduction for this, but rapidly disconnecting then reconnecting a bot (full service provider teardown and rebuild), seems to be able to trigger this error case here:

https://github.com/Nihlus/Remora.Discord/blob/85385a82e2e3a73aa4a86753bd0396505733b009/Backend/Remora.Discord.Gateway/DiscordGatewayClient.cs#L829-L836

My case is 2-4 bots using the same token running an integration test simultaneously in CI.

**Comment by Foxtrek64** [comment]
I'll add a change to the logging here to have it post what kind of event it actually receives and have it dump the raw output of that to the debug log.

Hopefully that tells us exactly what's happening.

**Comment by Foxtrek64** [comment]
So we have some proper test data:

Iteration 1 is not problematic:

```
info: Remora.Discord.ReadyPayload.Program[0]
      Iteration: 1
info: Remora.Discord.ReadyPayload.DiscordProvider[0]
      Gateway ready. Version 9
info: Remora.Discord.ReadyPayload.DiscordProvider[0]
      Stoptting gateway client.
warn: Remora.Discord.ReadyPayload.DiscordProvider[0]
      Gateway issue: The transport service is not connected.
```

The warning is there because I think even though `gatewayClient.RunAsync()` is called, it's not given enough time to run before it is aborted, so it never ends up actually connecting. Iteration 2 is where it gets interesting:

```
info: Remora.Discord.ReadyPayload.Program[0]
      Iteration: 2
info: Remora.Discord.ReadyPayload.DiscordProvider[0]
      Disconnect detected
info: Remora.Discord.ReadyPayload.DiscordProvider[0]
      Stoptting gateway client.
warn: Remora.Discord.ReadyPayload.DiscordProvider[0]
      Gateway issue: The payload after identification was not a Ready payload.
        Expected: Remora.Discord.API.Abstractions.Gateway.IPayload`1[[Remora.Discord.API.Abstractions.Gateway.Events.IReady, Remora.Discord.API.Abstractions, Version=53.0.0.0, Culture=neutral, PublicKeyToken=null]]
        Actual: Remora.Discord.API.Payload`1[[Remora.Discord.API.Abstractions.Gateway.Events.IInvalidSession, Remora.Discord.API.Abstractions, Version=53.0.0.0, Culture=neutral, PublicKeyToken=null]]
```

To make that easier to read:
Expected: IPayload<IReady>
Actual: IPayload<IInvalidSession>

I think we can pretty easily add in a case for this in the handler, though I welcome thoughts implementation.

**Comment by thaumanovic** [comment]
I encountered this shortly after Discord's outage the other day. Almost two full minutes passed between Remora attempting to create a new session and this error being encountered. An invalid session response seems likely. I had debug level logging enabled at the time but unfortunately nothing other than the error was logged.

**Comment by Cyberboss** [comment]
Appreciated!

**Comment by Nihlus** [comment]
A big thanks to everyone who worked to debug and resolve this issue. Wouldn't have been possible without you!
