### ISSUE TITLE
Getting Permssions of a Guild Member(Probably: Specifying Gateway Intents)

### ISSUE THREAD

**Issue by NoobyPilot** [Nihlus/Remora.Discord#123]
I have been trying to make certain parts of the bot only accessible to users with certain permissions, like manage server or administrator. While doing so, I have run into the issue, that the IGuildMember.Permissions field never has a value. Because of this, the best I can do is to assume they don't have the fitting permissions, which is obviously a problem if you want people to use the command. My best guess was, that the bot is missing the "SERVER MEMBERS INTENT", but even after turning it on, it didn't work because I didn't specify it in code. Here is where my problem lies now: I have fiddled around, but haven't been able to configure my gateway intents. I know this for a fact, since I  specified a custom activity for the bot aswell which won't show up either.
So this is my questions: **How/Where do I specify the Gateway Intents so that they actually end up working?**

Currently, I am trying to specify it on the ServiceCollection by using this bit of code:
`.Configure<DiscordGatewayClientOptions>(options =>
                {
                    options.Presence = new UpdatePresence(ClientStatus.Online, false, DateTimeOffset.Now, new[]
                    {
                        new Activity("Derping around", ActivityType.Custom,
                            Emoji: new ActivityEmoji("NinMEGADerp", new Snowflake(796895238044123196), false))
                    });
                    options.Intents = (GatewayIntents)0b111111111111111;
                })`

**Comment by Rutherther** [comment]
I think issues is not the best way to ask, you can ask on Remora official Discord server: https://discord.gg/tRJbg8HNdt.

As to your question, permissions field of GuildMember is used for permissions in channel if you want to get general server permissions of a user, you will have to check their roles permissions. Then use `DiscordPermissionSet.ComputePermissions` for joining all of the permissions for the member together.

I don't think you need to have that intent enabled, enabling `GuildMembers` intent would just subscribe to some more events and allow you to download all of the members using endpoint in guilds api.

Also if you were using Remora commands, you can use `RequireDiscordPermissionAttribute` on command methods or classes

**Comment by Rutherther** [comment]
sorry, to clarify `GuildMember.Permissions` should be specified only for interactions - application commands, message components etc., but in general you will have to get all the roles as I mentioned in the previous message.

**Comment by Nihlus** [comment]
Yeah, the server is better suited for questions like this. As @Rutherther said, this field is only populated when you receive the Guild Member object through an interaction; in other cases, you need to compute the permissions yourself.
