### ISSUE TITLE
IResponder<IMessageReactionAdd> not firing its Respond Async

### ISSUE THREAD

**Issue by tsandoe-coding** [Nihlus/Remora.Discord#125]
![image](https://user-images.githubusercontent.com/52936278/141672590-f4d39604-ac54-4de2-95be-c7480075650b.png)

My break point at the start is not being touched. Is this due to any recent discord API changes?

I've registered the responder with .AddResponder<ReactionAddedResponder>() in my services, just like I registered a IResponder<IMessageCreate> which is working fine.

Any insight into this problem would be wonderful. When I react to any message in the server where the bot is located, it's not being touched.

Thank you for your help,
Tyler

**Comment by Rutherther** [comment]
You can ask questions on Remora Discord: https://discord.gg/tRJbg8HNdt, that is probably better than asking here.

For receiving reactions you have to enable intent `GatewayIntents.GuildMessageReactions` you can do that by configuring `DiscordGatewayClientOptions` in your services setup
