### ISSUE TITLE
Better enum parameters slash command registration

### ISSUE THREAD

**Issue by Rutherther** [Nihlus/Remora.Discord#144]
I would like to propose a few features for registering enums when registering them as parameters for slash commands. Some of these were mentioned on the Discord server. 

- Add possibility to exclude some fields of the enum with some kind of exclude attribute
- Add support for registering nullable enums (currently in `CommandTreeExtensions` there is only `IsEnum` check, so nullable enums aren't treated properly)
- Add support for registering enums in Optional<>, same as the previous point (?)
- Add possibility to add Description of enum fields using `DataAnnotations.DisplayAttribute` (?), currently Remora's `DescriptionAttribute` is supported

**Comment by Nihlus** [comment]
Done.
