### ISSUE TITLE
Test fails because of locale

### ISSUE THREAD

**Issue by phidevz** [Nihlus/Remora.Discord#157]
The following line fails the test because of localization: 

https://github.com/Nihlus/Remora.Discord/blob/13aa9dd4da25916968c25d6b339daa1984854da7/Tests/Remora.Discord.Commands.Tests/Parsers/OneOfParserTests.cs#L94

Comma separator in Germany is `,` instead of `.`.

**Suggestion**: Make Remora.Discord culture invariant, but allow the use to use their current locale through an environment variable or Microsoft.Extensions.Configration-style `Configure<RemoraLocalization>(...)` method (`IOptions<RemoraLocalization>`)

**Comment by Nihlus** [comment]
This is a bug in https://github.com/Nihlus/Remora.Commands, not Remora.Discord - I've gone ahead and fixed the issue there, ensuring all parsing follows the invariant style. Thanks!
