### ISSUE TITLE
Deprecation of $ prefix in IIdentify connection fields [API v11]

### ISSUE THREAD

**Issue by MazeXP** [Nihlus/Remora.Discord#205]
In API v11 the $ prefix of the connection fields will be removed and are deprecated by now.

**Related docs PR** https://github.com/discord/discord-api-docs/pull/5067

**Related source**
https://github.com/Nihlus/Remora.Discord/blob/master/Backend/Remora.Discord.API/Extensions/ServiceCollectionExtensions.cs#L147-L150

**Comment by AraHaan** [comment]
Easy for me to grab this 👌.
