### ISSUE TITLE
PropertyErrorDetailsConverter fails to deserialise Auto Mod rule limit exceeded error

### ISSUE THREAD

**Issue by Hamsterland** [Nihlus/Remora.Discord#208]
**Description**
If you try to `CreateGuildAutoModerationRuleAsync` but your guild has reached the maximum number of rules, then the API will result in an error.
```json
{
    "code": 50035,
    "errors": {
        "_errors": [
            {
                "code": "AUTO_MODERATION_MAX_RULES_OF_TYPE_EXCEEDED",
                "message": "Maximum number of rules with trigger type 1 is 3."
            }
        ]
    },
    "message": "Invalid Form Body"
}
```
However, `PropertyErrorDetailsConverter` fails to deserialise this correctly.

**Steps to Reproduce**
1. Create three AutoMod rules of type `Keyword` type in your guild
2. Create a fourth `Keyword` type rule via `IDiscordAutoModerationAPI.CreateGuildAutoModerationRuleAsync`

**Expected Behavior**
The maximum rule count exceeded error is deserialised into the result.

**Current Behavior**
The deserialisation fails because the start token type is not `StartObject`, it is `StartArray`
![image](https://user-images.githubusercontent.com/57412787/174500956-9e0d8562-bd32-4adc-ad2a-066173cf8ce0.png)
`

**Library / Runtime Information**
.NET 6
Not sure which Remora version I'm working on but it's pretty recent.

**Comment by Nihlus** [comment]
This is explicitly handled, and is working fine in unit tests. Perhaps you're encountering another error?

**Comment by Hamsterland** [comment]
It's something for sure, it is definitely throwing. I'll create a minimumal reproducable example tomorrow.

**Comment by Hamsterland** [comment]
I created a MRE, but the error has gone away! The start token is still not StartObject - it is StartArray. But the final result does deserialize correctly. Whether this is intended or not I am unsure, but it works, so I'll close this for now.
