### ISSUE TITLE
Create a system for notifying us when the Discord API changes

### ISSUE THREAD

**Issue by Nihlus** [Nihlus/Remora.Discord#21]
Discord are quite good at not documenting their changes, nor being very clear when they update their docs to reflect changes. It'd be nice to have some sort of badge or alert system in place to show which version of the docs the library is built against (a commit ref, perhaps?).

**Comment by JakenVeina** [comment]
Should be able to get a fair bit of coverage from https://github.com/JakenVeina/Remora.Discord.Gateway.Assistant.

**Comment by Nihlus** [comment]
Absolutely!

**Comment by Nihlus** [comment]
We have a github feed in our Discord server; that will suffice for now.
