### ISSUE TITLE
[Discussion] Generalize record inheritance

### ISSUE THREAD

**Issue by MazeXP** [Nihlus/Remora.Discord#214]
**Description**
Currently the inheritance is not being done consistent for records in the code base.
First of all is the inheritance of objects just given by their interface. (e.g. `PartialMessage` and `Message`)
In other cases some records inherit from another record. (e.g. `Message` and `MessageCreate`)
The last case causes problems when the specialized record would change the type of the general record.

The later causes problems when a specialized property would change the type of the generalized property.
For example the `Mentions` property of `Message` is of type  `IReadOnlyList<IUser>`
but the `Mentions` property of `MessageCreate` is actually of type `IReadOnlyList<IUserMention>`.
Due to the record inheritance the underlying property would be of type `IReadOnlyList<IUser>`
but the `IMessageCreate` interface expects it to be of type `IReadOnlyList<IUserMention>`.

Therefore I would propose for all gateway events to also remove the inheritance from the inner payload
so that the properties are of the actual type of the interface and have the inheritance being handled by interfaces.
As one should nevertheless actually reference the interface types instead of the implementation types.

**Why This is Needed**
It would allow that the record does have the proper underlying property type.

**Alternatives**
Modify Remora.Rest's DataConverter that it would take the most generalized property when
multiple properties with the same name are returned by `GetPublicProperties()`.

**Additional Details**
[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0ATEBqAPgAQAYACfARhQG4BYAKDvwGZiBLAOwBcYoAzAQzAxiASQCqAZ250A3sTl0AvnQbN2XXgKFjJUALIxOLCG2IgREqbWmLltJq07d+gkfvHi+Acxgy6cucIASjB8GADybAA2AJ4AMiziHAA82twAfMT6hsbixLLeHJTESrQlKg7qzlpuHt4AwrB8XKauMO5ePlZ+/mwwAO4iwaERMfGJKRZ6BhxGbBlZMzl5xAVFJf7E3QFD4VFxCcmpUBnCNR0AdAuzuQC8GRwAFgmX09c0pbYA9J/EACpPuWMQgAVgBXRLEPrQADWuT4uUeQjUTk0xAwEDaxAefAAbkIYAgAA6RFhgFgcYg8aB9PhQDDsTzEQlQCCE7gzNrncqwSB04gAQUi6jYTRYeLO9UaXAAFFtBiFdqMDhMdFdjPNXjk6ABKFqnNq1GANEJcd7cmC8jCZA0dWW0DZBBUjfbjI4a7JscQ6vUSmBm2jfYgAdRYkUixDYEApUKg0OI8OIiJWBm4TRgVuZrPZ0Up0GtHtyUNBkStwCEEB4ieibOIACJHcM9mNDpM0rXzZbre1JSaYHaHTtnc2Vdw1XN84tPd6zL7+/4x17aNq0K1u0apZ1rPb/IGQ2HiGA+OChI8mnWAOIwDgABVBwBJYGvLLZUA54lrpAA7AioRPrkzn3ZFhMT6ckHjRFgeB4bhpirNk5XsXoBgbRUXRbVVNXHBc5S3DYNgKYg7mIaUUKHZUjjHNJtWAeEYBeAt3jw/x2HJQiMhoyR6MnW5iBxPhIlBP05RKMpaCAA==
) sample with the problem.

**Comment by Nihlus** [comment]
To be clear, I'm down for making this change - this issue is primarily here to catch any conflicts in existing code.

**Comment by MazeXP** [comment]
I think this should be closed as off https://github.com/Nihlus/Remora.Discord/commit/6426de6f0b5a50c610c5825503c2ab6d06a6a88a
