### ISSUE TITLE
WebSocket Abstract

### ISSUE THREAD

**Issue by kim-hong-gye** [Nihlus/Remora.Discord#224]
### Description

Hello ! Current library has hard depend on `ClientWebSocket` in [WebSocketPayloadTransportService](https://github.com/Nihlus/Remora.Discord/blob/master/Backend/Remora.Discord.Gateway/Transport/WebSocketPayloadTransportService.cs).

Request abstraction for websocket such like `IWebSocketClientFactory`, `IWebSocketClient`, allow for other websocket provider to be used. Can keep use WebSocketReceiveResult like ClientWebSocket as public API or custom, thin wrapper ideal. Structure this way ensure more idiomatic IoC code, specific web socket client should not be implement detail of Gateway client.

#### Example

```cs
// implement service can configure via DI, transparent to consumer
interface IWebSocketClientFactory
{
    IWebSocketClient Create();
}
```

```cs
interface IWebSocketClient
{
  // Maybe custom enum only properties library observe / care for
  WebSocketState State { get; }
  Task ConnectAsync(Uri uri, CancellationToken ct);
  Task CloseAsync(WebSocketCloseStatus closeStatus, string? description, CancellationToken ct);
  // Re-use WebSocketReceiveResult or custom?
  Task<WebSocketReceiveResult> ReceiveAsync(Memory<byte> buffer, CancellationToken ct);
}
```

### Why This is Needed

Working on project for benchmark .NET library for Discord, not able to test Remora same way as other library because hard depend ClientWebSocket.

Also ensure no future issue if library use in context ClientWebSocket not available / deprecate / incompatible.

### Alternatives Considered

Current benchmark rely on Harmony for patch ClientWebSocket ([example](https://github.com/kcut/institute-of-performance-research/blob/master/src/%EC%84%B1%EB%8A%A5%EC%97%B0%EA%B5%AC%EC%86%8C.Remora/ClientWebSocketPatches.cs)). Because different method to other benchmark, possible not as accurate (believe not worse penalty than network access real usage, patch return result direct - skip original code). Benchmark also cannot run some platform (mac OS) as Harmony not compatible. Not good !

### Additional Details

All detail above. Thank you 😸  !

**Comment by Nihlus** [comment]
The WebSocketTransportService is intended to use a real websocket, and adding a separate abstraction for the socket itself is out of scope for the library. The gateway client doesn't depend on WebSocketTransportService, but rather the `IPayloadTransportService` interface (https://github.com/Nihlus/Remora.Discord/blob/master/Backend/Remora.Discord.Gateway/DiscordGatewayClient.cs#L77).

If you want to mock the transport service, simply implement `IPayloadTransportService` and replace it in the DI container - I do this for the gateway tests, which you can read through here: https://github.com/Nihlus/Remora.Discord/blob/master/Tests/Remora.Discord.Gateway.Tests/Transport/MockedTransportService.cs

If this is not applicable, please describe your use case in more detail and I'll reopen the issue if neccesary.

**Comment by Nihlus** [comment]
Neither are likely to change, and, as I said, the intended abstraction level is on the transport service, not the socket itself. I might look at abstracting the websocket itself in the future, but it's not a priority at the moment.

**Comment by kim-hong-gye** [comment]
Thank you for understand ! since not priority but future investigate, not completed, can please re-open issue to ensure not forgotten ? Would be also easy first contribute for other remora user , as websocket abstract very simple quick to do .

Alternative you create new issue for track if discussion here not useful 😸 !
