### ISSUE TITLE
Unexpected Websocket Disconnect leaves DiscordGatewayClient in the wrong state

### ISSUE THREAD

**Issue by Nikey646** [Nihlus/Remora.Discord#23]
When the WebSocket closes unexpected and doesn't complete the entire handshake, the `DiscordGatewayClient._connectionStatus` field remains as `GatewayConnectionStatus.Connected`. This means any calls to `DiscordGatewayClient.RunAsync` afterwards will result in receiving a run result with the message "Already Connected.", however this isn't correct. It also appears if the client ends up in a Disconnected state and the loop inside of the DiscordGatewayClient ends, it'll have the same issue.

An unexpected WebSocket closure can be simulated via disconnecting and reconnecting to the internet, and causes this issue 100% of the time.

Using a Debugger (or presumably, reflection) to change the _connectionStatus property to Offline results in the DiscordGatewayClient successfully reconnecting.

**Comment by Nihlus** [comment]
Nice catch - this should be fixed momentarily.

**Comment by Nikey646** [comment]
This has been fixed.
