### ISSUE TITLE
Code Analysis prevents successful build

### ISSUE THREAD

**Issue by JakenVeina** [Nihlus/Remora.Discord#29]
**Description**
Using a brand new clone of the repository, the solution does not build, for me. I get the following build errors for every project:

```
CA0055 : Could not identify platform for 'D:\Projects\Remora.Discord\Samples\DiceRoller\bin\Debug\net5.0\DiceRoller.dll'.
```
```
CA0063 : * Failed to load rule set file 'D:\Projects\Remora.Discord\/stylecop.ruleset' or one of its dependent rule set files. The file does not conform to the rule set schema.
```
```
CA0064 : No analysis was performed because the specified rule set could not be loaded or did not contain any managed code analysis rules.
```

[This issue](https://github.com/dotnet/roslyn-analyzers/issues/1313) seems to be relevant. It seems in some fashion the `<RunCodeAnalysis>` tag in `Directory.Build.props` is being phased out? Setting it to `false` fixes the build completely.

Are there additional steps to setup the solution for building, or components that need to be installed to Visual Studio? If so, these should be described in a section of the readme or wiki regarding contributing.

**Steps to Reproduce**

Clone the repository, open the solution, and attempt to build it.

**Expected Behavior**

The solution should build with minimal effort from the developer. Any extra setup efforts that the developer needs to perform should be documented somewhere in the project readme or wiki.

**Current Behavior**

The solution does not build.

**Library / Runtime Information**

Running Visual Studio Community 2019, upon commit 6cacf4da.

**Comment by Nihlus** [comment]
Aha, interesting. Since it's unrelated to Roslyn analyzers, which are the only analysis tools in use, let's just remove it.
