### ISSUE TITLE
Missing service registration for ExecutionEventCollectorService

### ISSUE THREAD

**Issue by JakenVeina** [Nihlus/Remora.Discord#31]
**Description**

`ExecutionEventCollectorService` is requested as a dependency by `CommandResponder`, but is not registered with the IoC container.

**Steps to Reproduce**

Run the `DiceRoller` sample application, as-is, and attempt to execute the `!rolldice` command, or simply add the `ValidateOnBuild = true` option to the service provider in `Program.cs` line 78.

**Expected Behavior**

Sample applications built-in to the project should work, as-is.

**Current Behavior**

An `InvalidOperationException` is thrown: 

```
Unable to resolve service for type 'Remora.Discord.Commands.Services.ExecutionEventCollectorService' while attempting to activate 'Remora.Discord.Commands.Responders.CommandResponder'.
```

**Library / Runtime Information**

Using Visual Studio Community 2019, upon commit 6cacf4da.

**Comment by JakenVeina** [comment]
I've looked into this a bit more. 6cacf4d is not a fix for this because [line 70](https://github.com/Nihlus/Remora.Discord/blob/6cacf4da0ef85e2d1ec7aff9e9258a44f28335b6/Remora.Discord.Commands/Extensions/ServiceCollectionExtensions.cs#L70) is skipped if slash commands are disabled ([line 66](https://github.com/Nihlus/Remora.Discord/blob/6cacf4da0ef85e2d1ec7aff9e9258a44f28335b6/Remora.Discord.Commands/Extensions/ServiceCollectionExtensions.cs#L66)).

If `ExecutionEventCollectorService` is only necessary for slash commands, it can be configured as an optional dependency for `CommandResponder` by supplying a default value ` = null` for the parameter, within the constructor.

**Comment by Nihlus** [comment]
The event collector service is used for any command type, not just slash commands. It should be moved before the slash command-specific services - good catch!
