### ISSUE TITLE
.NET 6 - Determine PropertyInfo Nullability

### ISSUE THREAD

**Issue by Foxtrek64** [Nihlus/Remora.Discord#59]
**Description**

.NET 6 is slated to introduce a new `NullabilityInfo` type which accepts a `PropertyInfo` as a constructor argument. Example consumption:

```cs
private NullabilityInfoContext _nullabilityContext = new NullabilityInfoContext();

private void DeserializePropertyValue(PropertyInfo p, object instance, object? value)
{
    if (value == null)
    {
        var nullabilityInfo = _nullabilityContext.Create(p);
        var allowsNull = nullabilityInfo.State != NullableState.NotNull;
        if (!allowsNull)
            throw new MySerializerException($"Property '{p.GetType().Name}.{p.Name}'' cannot be set to null.");
    }

    p.SetValue(instance, value);
}
```
**Why This is Needed**

This will allow us to rewrite our `PropertyInfo.AllowsNull()` extension method into something as simple as this:
```cs
public static bool AllowsNull(this PropertyInfo property)
{
    var nullabilityInfo = new NullabilityInfoContext().Create(property);
    return nullabilityInfo.State != NullableState.NotNull;
}
```

**Additional Details**
The change for this can be found here: https://github.com/dotnet/runtime/issues/29723

**Comment by Nihlus** [comment]
Very nice. Once .NET 6 rolls around, I'll definitely consider it.

**Comment by Foxtrek64** [comment]
Closed - Moved to Remora.Commands
