### ISSUE TITLE
Allow for per-guild-tenant configurations on the default CommandResponder object.

### ISSUE THREAD

**Issue by RubyNova** [Nihlus/Remora.Discord#60]
**Description**

I've run into an issue with a bot I am developing for a friend of mine, but wanted to make the bot more configurable. Based on my understanding, I'll have to implement a custom command handler to do it properly, or just hack in some kind of KVP store with Redis to get around the issue. For something that seems minor, it feels a bit clunky to be implementing a custom responder.

**Why This is Needed**

This is needed, IMO, to provide a better UX in cases where the tweaks are minor, and not requiring full customisation. I may end up doing a full responder implementation myself regardless, but going forward for others, I feel this would be something that's nice to have.

**Alternatives Considered**

As stated previously, I could just implement my own custom responder object, but that feels pretty overkill for what I'm trying to do.

**Additional Details**

N/A

**Comment by Foxtrek64** [comment]
Your understanding is correct. I ran into this issue as well.

Not quite sure what the best generic option is yet, but I ended up having to roll my own to accomplish this.
