### ISSUE TITLE
Allow sending presence information as part of initial gateway identify

### ISSUE THREAD

**Issue by vaindil** [Nihlus/Remora.Discord#62]
**Description**

Discord's gateway [Identify command](https://discord.com/developers/docs/topics/gateway#identify) allows setting an initial presence. Remora.Discord's [IIdentify](https://github.com/Nihlus/Remora.Discord/blob/master/Backend/Remora.Discord.API.Abstractions/API/Gateway/Commands/IIdentify.cs) command has a property for this, but it doesn't seem to be exposed in a way that the standard `DiscordGatewayClient.RunAsync()` function would use. Could this be added somewhere, maybe to `DiscordGatewayClientOptions` (or wherever it would make sense)?

**Why This is Needed**

Discord supports this natively, and it would be nice to have. When my bot connects, it currently flashes the standard presence for a moment before my workaround is applied.

**Alternatives Considered**

Unless I'm missing something, it seems like the only way to accomplish this currently is to wait until the `IReady` event is received and manually fire `IUpdatePresence` at that point, which is a little hacky considering Discord natively supports supplying it with the initial identify handshake.

**Additional Details**

N/A. Thanks for the work on the library!

**Comment by Nihlus** [comment]
This is a good suggestion :) I'll see what I can do!

**Comment by Nihlus** [comment]
Fixed - you can now provide an `IUpdatePresence` object for the initial connection via `DiscordGatewayClientOptions`.
