### ISSUE TITLE
The int parser does not seem to work for negative values.

### ISSUE THREAD

**Issue by TraceLD** [Nihlus/Remora.Discord#63]
As per the title. When using a command with `int something` parameter, it works when the value is positive (i.e. greater than or equal to 0) but does not work for negative values, it simply does not find a matching command in that case.

Remora package versions:

![image](https://user-images.githubusercontent.com/46228022/119315907-3d8ce380-bc6e-11eb-853f-332cb80c3c88.png)

**Expected behaviour:**

Command is matched for both negative and positive values.

**Actual behaviour:**

```cs
[Command("reject", "r")]
[Description("Rejects a member application.")]
[RequireUserGuildPermission(DiscordPermission.BanMembers)]
public async Task<IResult> Reject(int id, [Greedy] string reason)
```

results in the following behaviour:

![image](https://user-images.githubusercontent.com/46228022/119315702-09192780-bc6e-11eb-80a2-cef2d7449a62.png)
![image](https://user-images.githubusercontent.com/46228022/119315737-12a28f80-bc6e-11eb-9bcf-284ea45dc86a.png)

**Comment by Nihlus** [comment]
This is an issue with Remora.Commands, not Remora.Discord. That said, the issue has been fixed, and will be patched in the next release :)
