### ISSUE TITLE
IOptional.HasValue has confusing name.

### ISSUE THREAD

**Issue by Foxtrek64** [Nihlus/Remora.Discord#64]
**Description**

The naming of `IOptional.HasValue` implies that it is a value check, i.e. a nullability check.

**Steps to Reproduce**

```cs
var foo = new Optional<string?>(null);
if (foo.HasValue)
    Console.WriteLine(foo.Value.Length); // NullReferenceException
```

**Library / Runtime Information**

Remora.Discord.Core v2.2.1

**Resolution**

```cs
public interface IOptional
{

    [Obsolete("Prefer IOptional.IsSpecified")]
    public bool HasValue { get; }

    public bool IsSpecified { get; }
}

public readonly struct Optional<TValue> : IOptional
{

    [Obsolete("Prefer IOptional.IsSpecified")]
    public bool HasValue => IsSpecified; // For backwards compatibility

    public bool IsSpecified { get; }
}
```

Credit to @JakenVeina for pointing out this issue.

**Comment by Nihlus** [comment]
I'll consider this issue closed with the release at c39b05d, where I merged the mentioned improvements to `Optional<T>`'s nullability annotations.
