### ISSUE TITLE
Selected values of Menu-Select feature are missing from  ApplicationCommandInteractionData

### ISSUE THREAD

**Issue by ProIcons** [Nihlus/Remora.Discord#78]
**Description**
Discord's Feature [Select-Menus](https://discord.com/developers/docs/interactions/message-components#select-menus) is not working properly because whenever you select a value, you never get the actual selected values from 
[ApplicationCommandInteractionData.cs#L34-L43](https://github.com/ProIcons/Remora.Discord/blob/master/Backend/Remora.Discord.API/API/Objects/Interactions/ApplicationCommandInteractionData.cs#L34-L43)

**Steps to Reproduce**

- Create a Responder for `IInteractionCreate`
- Create a Menu-Select with some options
- Send interaction to gateway
- Select a value from Discord
- This value won't be visible in `gatewayEvent` of the Responder

I tried to see if that's the case an i added 
```cs
Optional<IReadOnlyList<string>> Values { get; }
```
on ApplicationCommandInteractionData
And it returned the selected values as strings.

**Comment by Nihlus** [comment]
This is a known issue, and I've been waiting on Discord to document that field. See discord/discord-api-docs#3457.

**Comment by Nihlus** [comment]
Fixed.
