### ISSUE TITLE
System.Drawing APIs are going to be default disabled soon on Non-Windows Systems.

### ISSUE THREAD

**Issue by AraHaan** [Nihlus/Remora.Discord#94]
**Description**
The .NET Team that works on .NET 6 currently has the Unix aspects of all of the types in the System.Drawing APIs throw by default ``PNSE`` unless one opts-in to the old behavior. In .NET 8 the old behavior will be completely removed.

As such I noticed that the latest nuget packages to Remora uses System.Drawing.Color for some of the apis, as such those APIs *may* not be usable because they do not want to maintain libgdiplus that was made by the mono project originally for linux and macos users (unix based systems). Plus that libgdiplus has some issues that the Windows specific one does not have.

**Steps to Reproduce**
Install the Remora.Discord nuget package then look into the IL with Rider, you will notice the usage of ``System.Drawing`` based API's.

**Expected Behavior**
For non-System.Drawing based APIs to avoid ABI breakage when .NET 6 releases in November.

**Current Behavior**
The public API surface of Remora uses System.Drawing APIs that will throw PNSE when targeting the .NET 6 runtime (I think it already does it in the rc.1 daily quality builds).

**Library / Runtime Information**

Remora.Discord: 3.0.52
.NET Runtime: 6.0.100-rc.1.21413.11

**Comment by Nihlus** [comment]
That's interesting. Does MS have a proposed alternative for a type representing a colour?

**Comment by Nihlus** [comment]
Actually, we seem to be safe - this is only for the `System.Drawing.Common` nuget package, which Remora does not use.

**Comment by AraHaan** [comment]
Ah
