### ISSUE TITLE
Add function to check if the Gateway client's gateway intent configurations contains a specific gateway intent option.

### ISSUE THREAD

**Issue by AraHaan** [Nihlus/Remora.Discord#95]
**Description**
Currently there is no public facing api function that checks within the gateway client's own used ``DiscordGatewayClientOptions`` for if that instance has a specific intend within it's gateway intent options.

**Why This is Needed**
For example ``DiscordGatewayClientOptions`` by default comes with the following intents set ``GatewayIntents.Guilds`` and ``GatewayIntents.GuildMessages``. While that is nice and all, others might use DI to manually construct that object in order to specify all of the intents, and might need to debug if the library is properly handling each set intent option properly and that the library can properly get the events for each of the gateway intents that they want / need for their bot to work.

**Alternatives Considered**
None yet, other than having the library log when it sees a specific event being sent to it.

**Additional Details**

**Comment by AraHaan** [comment]
After further investigation into this by doing this inside of my ReadyResponder I discovered there is a bug in the library which makes the values that people specify for intents getting overridden with the default ones (oops) at least when running under the .NET 6 runtime. I noticed this as well before on my own code and that is why I had some breakage from old behavior when I used to define properties like this to avoid setting them inside of the the default constructor.

https://gist.github.com/AraHaan/3a5d7da40d39750dd481612cf5f05d88

As such I think the best option is to move these to a public or internal default constructor for that options type so then that way the user provided values do not get overridden after setting when you try to ``get`` from that property it seems to do the operation after the ``=`` in their definitions resulting in the value the user explicitly defined in their DI container to be reset accidentally.

**Comment by Nihlus** [comment]
The simplest way to do this is to inject `IOptions<DiscordGatewayClientOptions>` into whichever of your classes that need it; I don't see a need to expose it directly on the client. Exposing it would also mean it could be modified after injection, since the options type is not immutable (which, admittedly, is a fixable issue).

 I know you're setting up a minimal repro for the second issue, which we'll have to investigate further. I've been unable to reproduce it on my end.

**Comment by AraHaan** [comment]
I have since then resolved this.
