### ISSUE TITLE
Emojis in messages

### ISSUE THREAD

**Issue by NoobyPilot** [Nihlus/Remora.Discord#96]
**Description**

I am writing a bot for a community and to ahve the bot do what I need it to do, I need to be able to recognise emjis in messages that are being sent, but instead of an emoji like ":heart:" I end up getting "??" which, obviously, makes it very hard to use. I have noticed that the problem only exists for some emojis, as custom emojis get translated perfectly to their usual format (<:name:id>).

**Why This is Needed**

There is a lot of bots that do things like logging, quotes and similar things that require an accurate display of the message that was sent, including emotes for some situation. While it isn't something that makes the library unusable, it is quite the pain

**Alternatives considered**

I wanted to try substituting the "??" for emotes used, but since the emotes can't be gotten from the IMessageCreate event, that wasn'T possible

**Additional Details**

N/A

**Comment by Nihlus** [comment]
Can you provide examples of what you're seeing? It may be that you're getting unicode escape sequences, which are completely valid, but simply look strange.

**Comment by NoobyPilot** [comment]
Sure, I have this test message and the fitting log output which just displays "??" to me and then saves exactly that into the database.

![testMessage](https://user-images.githubusercontent.com/43069144/130467877-11321769-6708-4307-b06a-aa8786908290.PNG)
![logOutput](https://user-images.githubusercontent.com/43069144/130467881-626cd045-2d85-4ec9-91a6-d5d5971ce49e.PNG)

**Comment by Nihlus** [comment]
I'm unable to reproduce this. Can you provide a minimal repro?

**Comment by NoobyPilot** [comment]
Sure, I quickly put this together, that results in the same problem for me
[test.txt](https://github.com/Nihlus/Remora.Discord/files/7033190/test.txt)

**Comment by Nihlus** [comment]
Which emojis have this issue? I tried with a heart, plus some others, and still could not reproduce.

**Comment by NoobyPilot** [comment]
For me the issue comes with most of the default emojis, like the heart, thumbsup/down etc

**Comment by fujista** [comment]
This appears to be a problem on the console side, not the library side.
I have confirmed that the `QuotesResponder` is receiving the emoji correctly.
Basically, the Windows console is not capable of displaying emoji.

If you really want to display them on Windows, set the console character encoding to UTF-8 and use a program such as "Windows Terminal" that supports the display of emoji.
Also, check the character encoding of your database, which is probably not set to support emoji.

**Comment by Nihlus** [comment]
Yeah, this seems like a lack of UTF-8 support, not a library bug. Could you try with another terminal that supports UTF-8, and verify your database like @fujista suggested?

**Comment by NoobyPilot** [comment]
Yeah, after seeing you guys not being able to reproduce the problem I assumed it was not library side, but somewhere on my end, but since I stored the message in a database to later print it, I got into contact with a Database Admin for the database I use and I was able to figure the problem out. Thanks for all of the help anyways.

And for anyone using Microsoft SQL Server: Unicode not only requires the n- types (like nvarchar), you also need to change your string from 'string' to N'string'
