### ISSUE TITLE
Make GatewayConnectionStatus public

### ISSUE THREAD

**Issue by Cyberboss** [Nihlus/Remora.Discord#97]
**Description**

Please expose `DiscordGatewayClient._connectionStatus` as a property or add a callback for when the initial gateway connection iteration is completed.

**Why This is Needed**

Currently after calling `DiscordGatewayClient.RunAsync` there's no way to guarantee from client code that either:
a) The connection has been successful
or
b) The connection ended in failure

My program wants to (asynchronously) block until one of these conditions is met.

**Alternatives Considered**

Here's a workaround using reflection
```cs
var gatewayTaskLocal = gatewayClient.RunAsync(gatewayCancellationToken);

// HACK: The gateway connection status isn't public, how 'bout we read it anyway?
GatewayConnectionStatus connectionStatus;
var connectionStatusField = gatewayClient.GetType().GetField("_connectionStatus", BindingFlags.NonPublic | BindingFlags.Instance);
do
{
	await Task.Delay(TimeSpan.FromMilliseconds(250), cancellationToken).ConfigureAwait(false);
	connectionStatus = (GatewayConnectionStatus)connectionStatusField.GetValue(gatewayClient);
}
while (!gatewayTaskLocal.IsCompleted && connectionStatus != GatewayConnectionStatus.Connected);

gatewayTask = gatewayTaskLocal;
if (gatewayTask.IsCompleted)
{
	await DisconnectImpl(cancellationToken).ConfigureAwait(false); // awaits `gatewayTask`
	throw new JobException(ErrorCode.ChatCannotConnectProvider);
}
```

**Comment by Nihlus** [comment]
If you want to run code when the gateway connection is ready for use, I'd suggest using an `IResponder<IReady>` - that event is fired once when the gateway client successfully connects, and when it successfully resumes. It'll be more reliable than checking the connection status, which is just an internal state tracking field that isn't guaranteed to say whether the client is properly connected or not.

That said, there is a new gateway client in the works, and exposing its connection state is something that has been considered.

**Comment by Cyberboss** [comment]
That helps immensely, thanks

**Comment by Nihlus** [comment]
@Cyberboss Are you satisfied with that solution for the time being? If so, I'll close this issue.

**Comment by Cyberboss** [comment]
Yeah that works for me
