### ISSUE TITLE
GatewayClient doesn't abort when providing an incorrect bot token

### ISSUE THREAD

**Issue by Cyberboss** [Nihlus/Remora.Discord#99]
**Description**

When calling DiscordGatewayClient.RunAsync with an invalid bot token provided, connection attempts will persist despite the HTTP 401 response.

**Steps to Reproduce**

```cs
	using var serviceProvider = new ServiceCollection()
		.AddDiscordGateway(serviceProvider => "fake")
		.BuildServiceProvider();

	await serviceProvider.GetRequiredService<DiscordGatewayClient>().RunAsync(default);
```

This will await indefinitely.

**Expected Behavior**

`RunAsync` returns an error `Result` expressing that the token is invalid.

**Comment by AraHaan** [comment]
I agree this sort of thing can result in a temp api ban from cloudflare. It happened to me yesterday and I was  wondering why nothing in Discord worked on the Discord clients or even on my phone until I looked at the phone Discord logs.

**Comment by Nihlus** [comment]
I'm surprised that this still happens - I thought I'd caught this in a recent patch. I'll investigate on Friday.
